/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERCMINTExt20__factory } from "./IERCMINTExt20__factory";
export { ITokenVault__factory } from "./ITokenVault__factory";
