/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as veToken from "./veToken";
export type { veToken };
export type { ExampleToken } from "./ExampleToken";
