/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameCoffer } from "./GameCoffer";
export type { GameCofferPaymentSplitter } from "./GameCofferPaymentSplitter";
