/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VestingByTimeBlockWalletUpgradeable__factory } from "./VestingByTimeBlockWalletUpgradeable__factory";
