/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameCoffer from "./gameCoffer";
export type { gameCoffer };
import type * as tokenUsdt from "./token-USDT";
export type { tokenUsdt };
import type * as tokenX from "./token-X";
export type { tokenX };
import type * as tokenY from "./token-Y";
export type { tokenY };
import type * as tokenCoffer from "./tokenCoffer";
export type { tokenCoffer };
import type * as vestingWallet from "./vestingWallet";
export type { vestingWallet };
export type { TokenDeposit } from "./TokenDeposit";
export type { TokenRedeem } from "./TokenRedeem";
