/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { USDTFaucet__factory } from "./USDTFaucet__factory";
export { XYGameUSDT__factory } from "./XYGameUSDT__factory";
